version: "3.9"

services:
  backend:
    build: ./backend
    container_name: genai-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: genai-postgres
    restart: always
    environment:
      POSTGRES_USER: genai
      POSTGRES_PASSWORD: genai123
      POSTGRES_DB: genai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: genai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
